#!/bin/bash
### BEGIN INIT INFO
# Provides: gwmon-api
# Required-Start: $local_fs $remote_fs $network $named
# Required-Stop: $local_fs $remote_fs $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop gwmon-api
# Description: gwmon-api
### END INIT INFO

case $1 in
    start)
        /opt/gwmon-api/gwmon-api.jar start
    ;;
    stop)
        /opt/gwmon-api/gwmon-api.jar stop
    ;;
    restart)
        /opt/gwmon-api/gwmon-api.jar stop
        /opt/gwmon-api/gwmon-api.jar start
    ;;
esac
exit 0
